#!/bin/bash

# Load the project properties
if [ -f ./gradle.properties ]; then
  . ./gradle.properties
fi
cp src/test/java/com/sololegends/runelite/WhatPetIsThatPluginTest.java src/main/java/com/sololegends/runelite/WhatPetIsThatPluginTest.java
./gradlew full
java -jar -ea build/libs/$sl_archivesBaseName-$sl_version.jar "$@"
rm src/main/java/com/sololegends/runelite/WhatPetIsThatPluginTest.java