image: gradle:6.0.1-jdk11

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

publish-latest-full:
  stage: deploy
  script:
    - apt update && apt install jq -y
    - sh remove_package.sh latest
    - gradle full -x test publish -Pverp=full -Pver=fulllatest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

publish-version-full:
  stage: deploy
  script:
    - gradle full -x test publish -Pverp=full
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

publish-latest-build:
  stage: deploy
  script:
    - apt update && apt install jq -y
    - sh remove_package.sh latest
    - gradle build -x test publish -Pver=latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

publish-version-build:
  stage: deploy
  script:
    - gradle build -x test publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
